### PR TITLE
Fix missing delete cascade on MessageThread

### PR DESCRIPTION
**Pull request by melroy89**
Hopefully solves:

```
{"message":"Error thrown while handling message App\\Message\\DeleteUserMessage. Removing from transport after 7 retries. Error: \"Handling \"App\\Message\\DeleteUserMessage\" failed: An exception occurred while executing a query: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table \"user\" violates foreign key constraint \"fk_f2de9290a76ed395\" on table \"message_thread_participants\"\nDETAIL:  Key (id)=(211639) is still referenced from table \"message_thread_participants\".\"","context":{"class":"App\\Message\\DeleteUserMessage","retryCount":7,"error":"Handling \"App\\Message\\DeleteUserMessage\" failed: An exception occurred while executing a query: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table \"user\" violates foreign key constraint \"fk_f2de9290a76ed395\" on table \"message_thread_participants\"\nDETAIL:  Key (id)=(211639) is still referenced from table \"message_thread_participants\".","exception":{"class":"Symfony\\Component\\Messenger\\Exception\\HandlerFailedException","message":"Handling \"App\\Message\\DeleteUserMessage\" failed: An exception occurred while executing a query: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table \"user\" violates foreign key constraint \"fk_f2de9290a76ed395\" on table \"message_thread_participants\"\nDETAIL:  Key (id)=(211639) is still referenced from table \"message_thread_participants\".","code":7,"file":"/var/www/kbin.melroy.org/html/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:124","previous":{"class":"Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException","message":"An exception occurred while executing a query: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table \"user\" violates foreign key constraint \"fk_f2de9290a76ed395\" on table \"message_thread_participants\"\nDETAIL:  Key (id)=(211639) is still referenced from table \"message_thread_participants\".","code":7,"file":"/var/www/kbin.melroy.org/html/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:50","previous":{"class":"Doctrine\\DBAL\\Driver\\PDO\\Exception","message":"SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table \"user\" violates foreign key constraint \"fk_f2de9290a76ed395\" on table \"message_thread_participants\"\nDETAIL:  Key (id)=(211639) is still referenced from table \"message_thread_participants\".","code":7,"file":"/var/www/kbin.melroy.org/html/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28","previous":{"class":"PDOException","message":"SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table \"user\" violates foreign key constraint \"fk_f2de9290a76ed395\" on table \"message_thread_participants\"\nDETAIL:  Key (id)=(211639) is still referenced from table \"message_thread_participants\".","code":23503,"file":"/var/www/kbin.melroy.org/html/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:130"}}}}},"level":500,"level_name":"CRITICAL","channel":"messenger","datetime":"2024-03-30T19:49:43.138338+00:00","extra":{}}
```

### CODE REVIEW

**Comment by melroy89** [comment]
Should `cascade: ['persist']` still be present?

**Comment by BentiGorlich** [comment]
> Should `cascade: ['persist']` still be present?

I don't know. I just copied it over from other code. I think we need to consult the symfony docs for it.

There is no migration attached to the PR, did you forget to push something? 😁

**Comment by melroy89** [comment]
Generate (`php bin/console doctrine:migrations:generate`) created an empty up & down!? THat is strange:

```
diff --git a/migrations/Version20240402140532.php b/migrations/Version20240402140532.php
new file mode 100644
index 00000000..24ccd1a0
--- /dev/null
+++ b/migrations/Version20240402140532.php
+<?php
+
+declare(strict_types=1);
+
+namespace DoctrineMigrations;
+
+use Doctrine\DBAL\Schema\Schema;
+use Doctrine\Migrations\AbstractMigration;
+
+/**
+ * Auto-generated Migration: Please modify to your needs!
+ */
+final class Version20240402140532 extends AbstractMigration
+{
+    public function getDescription(): string
+    {
+        return '';
+    }
+
+    public function up(Schema $schema): void
+    {
+        // this up() migration is auto-generated, please modify it to your needs
+
+    }
+
+    public function down(Schema $schema): void
+    {
+        // this down() migration is auto-generated, please modify it to your needs
+
+    }
+}
diff --git a/src/Entity/Message.php b/src/Entity/Message.php
index ec197905..d7ac1e0f 100644
--- a/src/Entity/Message.php
+++ b/src/Entity/Message.php
@@ -29,7 +29,7 @@ class Message
     ];
 
     #[ManyToOne(targetEntity: MessageThread::class, cascade: ['persist'], inversedBy: 'messages')]
-    #[JoinColumn(nullable: false)]
+    #[JoinColumn(nullable: false, onDelete: 'CASCADE')]
```

**Comment by melroy89** [comment]
Moreover, `nullable: false` now. In a change you created in the past migration: `Version20240317163312` shows also something like this to change the nullability to null.

**Comment by BentiGorlich** [comment]
> Moreover, `nullable: false` now. In a change you created in the past migration: `Version20240317163312` shows also something like this to change the nullability to null.

What do you mean?

**Comment by melroy89** [comment]
I mean. Maybe we can do cascade delete only if the join column nullalable is set to true.

**Comment by BentiGorlich** [comment]
yep, that is what @nobodyatroot agreed upon when we had the report cascading problem

**Comment by melroy89** [comment]
I will take a break.

**Comment by melroy89** [comment]
Thanks, too bad I can't approve my own PR.

**Review by e-five256 — APPROVED** [review]
ran it locally, db schema updated and could still delete users. might be worth having someone else check it out as well but seemed correct to me

**Pull request merged**
