### PR TITLE
Update composer + npm packages and Symfony 7.1 upgrade

### PR DESCRIPTION
**Pull request by nobodyatroot**
Update all composer + npm packages to their latest minor versions from existing package versions and upgrade to Symfony 7.1.

closes https://github.com/MbinOrg/mbin/issues/857

### CODE REVIEW

**Comment by nobodyatroot** [comment]
i have this running on kbin.run, no observed issues in any of the logs. tested federation, seems ok.

**Comment by BentiGorlich** [comment]
I have it running as well now

**Review by melroy89 — APPROVED** [review]
Did you also check for recipe updates?

**Comment by nobodyatroot** [comment]
> Did you also check for recipe updates? 

Yep, last two commits I added for doctrine and mercure had updates.

**Comment by melroy89** [comment]
> > Did you also check for recipe updates?
> 
> Yep, last two commits I added for doctrine and mercure had updates.

Ah yes. Great!

**Comment by melroy89** [comment]
That went well.. 😆

**Pull request merged**
