### PR TITLE
Update all npm packages and address dependabot security notice

### PR DESCRIPTION
**Pull request by nobodyatroot**
Closes:

image

### CODE REVIEW

**Comment by BentiGorlich** [comment]
Did you just run `npm upgrade` or `npm audit fix`?

**Comment by nobodyatroot** [comment]
> Did you just run `npm upgrade` or `npm audit fix`?

In this case I ran `npm update` since we haven't done it in awhile. To target the vulnerable notice only, then yea `npm audit fix` would take care of it.

**Comment by BentiGorlich** [comment]
I still get deprecation notices when running the `post-upgrade` script though :thinking:

**Comment by nobodyatroot** [comment]
> I still get deprecation notices when running the `post-upgrade` script though 🤔

Afaik, `npm update` won't forcibly remove/replace/change packages that could potentially break the build, I think it only updates to latest minor versions unless there's some explicit version pinning on a package that stops it.

**Pull request merged**
