### PR TITLE
Make social login more prominently visible part 1

### PR DESCRIPTION
**Pull request by TheVillageGuy**
Melroy was here: You could also update this description here instead of a new comment below ;)

### CODE REVIEW

**Comment by TheVillageGuy** [comment]
Before: 
image
After:
image

**Comment by e-five256** [comment]
These images don't seem to correspond to the changes, did you mean to do only https://github.com/MbinOrg/mbin/pull/642 ?

**Comment by TheVillageGuy** [comment]
The screenshots show the result of both this and #642

**Comment by melroy89** [comment]
Since you already combine those two PRs. I believe they belong together. Then also create a single pr with these changes together, I don't think two separate PRs are necessary.

**Pull request closed without merging**
