### PR TITLE
Improve error warning log pollution (Part 2)

### PR DESCRIPTION
**Pull request by melroy89**
- For developers: how to start a local development server
- Update various composer packages (incl. Symfony, phpstan, phpunit, doctrine, ..)
- Run composer recipes (messenger, validator, doctrine)
- Fix depreciation warnings/errors
- Fix additional null checks and `Undefined array key "href"`

### CODE REVIEW

**Review by TheVillageGuy — APPROVED** [review]
Deep sleep approval. It wasn't me

**Comment by melroy89** [comment]
I might want to run this pr for one or two days on acceptance before merging. Which you might understand.

**Comment by nobodyatroot** [comment]
I'm running this overnight as well on kbin.run and will check back in the morning.

**Comment by nobodyatroot** [comment]
So far so good. Other than the unique key violations that have been happening all along, I noticed the following below.

```
[2023-10-22T13:01:44.892960+00:00] messenger.CRITICAL: Error thrown while handling message App\Message\ActivityPub\Inbox\ChainActivityMessage. Removing from transport after 0 retries. Error: "Handling "App\Message\ActivityPub\Inbox\ChainActivityMessage" failed: Call to a member function getId() on null" {"class":"App\\Message\\ActivityPub\\Inbox\\ChainActivityMessage","retryCount":0,"error":"Handling \"App\\Message\\ActivityPub\\Inbox\\ChainActivityMessage\" failed: Call to a member function getId() on null","exception":"[object] (Symfony\\Component\\Messenger\\Exception\\HandlerFailedException(code: 0): Handling \"App\\Message\\ActivityPub\\Inbox\\ChainActivityMessage\" failed: Call to a member function getId() on null at /var/www/kbin/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:129)\n[previous exception] [object] (Error(code: 0): Call to a member function getId() on null at /var/www/kbin/src/MessageHandler/ActivityPub/Inbox/ChainActivityHandler.php:78)"} []
```

**Comment by melroy89** [comment]
LGTM until now..

**Comment by melroy89** [comment]
> So far so good. Other than the unique key violations that have been happening all along, I noticed the following below.
> 
> ```
> [2023-10-22T13:01:44.892960+00:00] messenger.CRITICAL: Error thrown while handling message App\Message\ActivityPub\Inbox\ChainActivityMessage. Removing from transport after 0 retries. Error: "Handling "App\Message\ActivityPub\Inbox\ChainActivityMessage" failed: Call to a member function getId() on null" {"class":"App\\Message\\ActivityPub\\Inbox\\ChainActivityMessage","retryCount":0,"error":"Handling \"App\\Message\\ActivityPub\\Inbox\\ChainActivityMessage\" failed: Call to a member function getId() on null","exception":"[object] (Symfony\\Component\\Messenger\\Exception\\HandlerFailedException(code: 0): Handling \"App\\Message\\ActivityPub\\Inbox\\ChainActivityMessage\" failed: Call to a member function getId() on null at /var/www/kbin/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:129)\n[previous exception] [object] (Error(code: 0): Call to a member function getId() on null at /var/www/kbin/src/MessageHandler/ActivityPub/Inbox/ChainActivityHandler.php:78)"} []
> ```

I will take this along for Part 3 I think.. 👍🏽 Again I stopped due to the size of this PR again. There is still so much mess in the code, that it might take several PRs to clean it all up. Thanks for noticing this message, I will take a look at it in my follow-up of this PR.

**Comment by melroy89** [comment]
Same about this: 

```
SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"url_idx\"\nDETAIL:  Key (url)=(https://www.frommers.com/blogs/arthur-frommer-online/blog_posts/california-bans-deceptive-resort-fees-see-what-s-affected-and-when) already exists. at /var/www/kbin.melroy.org/html/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:53)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"url_idx\"\nDETAIL:  Key (url)=(https://www.frommers.com/blogs/arthur-frommer-online/blog_posts/california-bans-deceptive-resort-fees-see-what-s-affected-and-when) already exists. 
```

**Comment by melroy89** [comment]
Mbin didn't like the doctrine upgrade.. 😢

**Pull request merged**
