### PR TITLE
Add `isAdmin` and `isGlobalModerator` fields to user api response

### PR DESCRIPTION
**Pull request by BentiGorlich**
Link #1001

### CODE REVIEW

**Comment by jwr1** [comment]
Would you be able to add this to the simple user fields as well? The way you have it, if an admin or global mod made a post about something, you would not be able to tell they are the admin until actually viewing their profile page (`/api/users/*`).

**Comment by jwr1** [comment]
Like this:
image

**Comment by BentiGorlich** [comment]
Done

**Review by melroy89 — APPROVED** [review]
LGTM

**Review by jwr1 — APPROVED** [review]
Just tried it, looks good to me!

**Pull request merged**
