### PR TITLE
Upgrade to Symfony 7.x, package updates and removal of deprecated features

### PR DESCRIPTION
**Pull request by nobodyatroot**
I followed this guide: https://symfony.com/doc/current/setup/upgrade_major.html

A few packages needed to get bumped to their latest version in order to support Symfony 7.x, so I had to modify a couple minor things here and there because either the naming changed or a feature is no longer supported.

~~**The biggest issue**: the ViewCounterBundle (https://github.com/tchoulom/ViewCounterBundle, https://packagist.org/packages/tchoulom/view-counter-bundle) does not support Symfony 7.x, but I was questioning whether this feature/stat is needed at all... it seems like unnecessary db overhead, but maybe someone uses it? Either way, we can't upgrade past 6.4 without replacement/removal or wait until the maintainer pushes a 7.x compatible version.~~

~~**EDIT**: It was brought to my attention (thanks @e-five256) that kbin has also removed the view counter & stats, so maybe not too unreasonable? Again, seems like extra overhead for little use.~~

View counter issue resolved in https://github.com/MbinOrg/mbin/pull/666

### CODE REVIEW

**Comment by asdfzdfj** [comment]
somewhat personal opinion but perhaps considering split the killing the view counter to a different branch/PR if you want to go down that way? should help with easier reviewing and maybe finding/fixing regressions if it endded up causing any

**Comment by nobodyatroot** [comment]
> somewhat personal opinion but perhaps consider split the view counter removal to a different branch/PR if you want to go down that way? should help with easier reviewing and maybe finding/fixing regressions if it ended up causing any

Yep, I was thinking the same thing after closing out last night. I'll split the PRs, but leave this one as draft since it depends on removing that unsupported package... and update this one once the remove view counter PR is approved.

**Comment by nobodyatroot** [comment]
I did a local upgrade from current main with test fixtures loaded to this branch, processed messages, deleted users, etc... no observed issues, but it'd be good if someone else can double check.

**Comment by BentiGorlich** [comment]
Ok, it's absolutely not your fault. I really don't know who broke it. It was broken on v1.5.2 as well and I guess basically since forever... Maybe it's just a dev mode problem? I really don't know, but here is the fix: #691

**Review by BentiGorlich — APPROVED** [review]
I clicked around a bunch, used the messengers a bit. Found nothing that this PR breaks, so :+1:

**Pull request merged**
