### PR TITLE
Introducing NodeInfo v2.1 support (+refactoring)

### PR DESCRIPTION
**Pull request by melroy89**
- Introducing NodeInfo v2.1 support
- Add missing `services` and `metadata`
- Small refactoring

### CODE REVIEW

**Review by BentiGorlich — CHANGES_REQUESTED** [review]
As far as I can tell the schema definition requires `services` and `metadata` properties. 
It is fine to have empty in- and outbound services and empty metadata tags, but they are required

**Comment by melroy89** [comment]
> As far as I can tell the schema definition requires `services` and `metadata` properties. It is fine to have empty in- and outbound services and empty metadata tags, but they are required

Ow let me check with: https://nodeinfo.diaspora.software/schema.html

**Comment by melroy89** [comment]
> Yeah mastodon keeps them empty as well. They are required in v2.0 as well. Funny that they were just ignored...

Let me see what this JSON formatter does in PHP, since the meta-data should be an object (in JSON) while the inbound and outbound should be of type array (in JSON). But PHP well just only has `[]` lol..

**Review by BentiGorlich — APPROVED** [review]

**Review by BentiGorlich — APPROVED** [review]

**Comment by melroy89** [comment]
> > Yeah mastodon keeps them empty as well. They are required in v2.0 as well. Funny that they were just ignored...
> 
> Let me see what this JSON Response formatter does in PHP, since the meta-data should be an object (in JSON) while the inbound and outbound should be of type array (in JSON). But PHP you just only have `[]` lol..

I fixed this by using `(object)[]` in PHP, that did the trick:

image

**Pull request merged**
