### PR TITLE
Add new instance table

### PR DESCRIPTION
**Pull request by BentiGorlich**
Add a new table with which we can track the software, version, last successful deliver and receive timestamp. 

The federation page now looks something like this:
grafik

| user panel | magazine panel |
| ---------- | -------------- |
| grafik | grafik |

The table will be populated with receives, nothing mandates an instance entry to be there, so there is not guarantee that there is an entry in the instance table for each user or magazine

There are 2 new API endpoints:
- `/api/federated` returns all instances we (knowingly) federate with
- `/api/dead` all instances considered dead by the instance

The `/api/defederated` endpoint will now return a list of `InstanceDto` like the other 2

Additionally users and magazines retrieved by the API now contain a `serverSoftware` and `serverSoftwareVersion` field

### CODE REVIEW

**Comment by jwr1** [comment]
Will this be in the API also?

**Comment by BentiGorlich** [comment]
Not yet... I literally always forget about the API 😅
I'll have a look at it tomorrow. What do you think would make sense? Just adding the general table to be queried? Or do you want it added to get the info for users (what server software they are using)? Or both?

**Comment by jwr1** [comment]
I was thinking both. Like a new key (e.g. `instance`) in the user object with information about the user's instance (you could also add this for magazines if you wanted). And then probably something like a `/api/intances` route to get the whole list of instances.

**Comment by BentiGorlich** [comment]
@jwr1 I added additional endpoints, see the updated PR info

**Comment by jwr1** [comment]
Looks great to me! Since the change to the defederated endpoint is backward incompatible, it'll break current uses of it though; joinmbin.org, for example, lists all 10 of gehirneimer.de's defederated servers as `[object Object]`. It's not that big of a deal, since I could easily fix it on the website, but it's something to note.

**Comment by BentiGorlich** [comment]
Yeah, I could make it just a v2 then... :thinking: 
I just thought that nobody is using it anyways

**Comment by jwr1** [comment]
> Yeah, I could make it just a v2 then... 🤔 I just thought that nobody is using it anyways

I'd say it's fine as is. I just think it's something we should mention in the release notes.

**Comment by BentiGorlich** [comment]
Should be fixed now. Actually a great call @jwr1 I created a bunch of problems with editing the banned instances which I created by modifying the InstanceDto

**Review by nobodyatroot — DISMISSED** [review]

**Comment by jwr1** [comment]
Wait, so does defederated v2 have an api route? I wasn't able to see it in the API docs.

**Comment by BentiGorlich** [comment]
I forgot to push it :D

**Review by jwr1 — DISMISSED** [review]

**Review by nobodyatroot — DISMISSED** [review]

**Comment by BentiGorlich** [comment]
I think there are problems with instances that only supply a 2.0 endpoint

**Comment by melroy89** [comment]
I see a very very limited list to be honest. The previous list was more complete?

image


https://kbin.melroy.org/federation

**Comment by melroy89** [comment]
Ow.. It seems to be slowly adding more and more...

image

**Comment by BentiGorlich** [comment]
Yes this list is built with incoming activities

**Review by nobodyatroot — APPROVED** [review]

**Review by melroy89 — APPROVED** [review]

**Pull request merged**
