### PR TITLE
Don't federate anything from the random magazine

### LINKED ISSUE #444: Stop federating /m/random
**Is your feature request related to a problem? Please describe.**
Unmoderated content from the random mag is federating to other servers.

**Describe the solution you'd like**
The random mag as the local catch all for posts and entries which can not be put into another magazine should not accept followers and should not announce posts in any way.

**Describe alternatives you've considered**
Don't even return it for the webfinger

**Additional context**

### PR DESCRIPTION
**Pull request by BentiGorlich**
- don't return the random magazine on webfinger requests
- don't federate anything outwards from the random magazine

Closes #444

### CODE REVIEW

**Comment by melroy89** [comment]
OK I think I agree maybe, but..

What if I got to a random thread like: https://kbin.melroy.org/m/random/t/64276/Lovecraft-s-Cthulhu-Mythos-Reading-Order#comments

And I place a comment.. Will that still just work? I think the users of my instance who comment there would like to get their comment federated out. At least I would.

**Comment by BentiGorlich** [comment]
yeah you're absolutely right. The author should still get the comments from us even if the thread is jn the random magazine... Gotta adjust the PR, pribably a lot...

**Comment by melroy89** [comment]
Let me try to run this on my instance. Just to check.

**Comment by BentiGorlich** [comment]
Sounds like a good idea

**Comment by melroy89** [comment]
> Sounds like a good idea

Seems to work? https://wehavecookies.social/@BentiGorlich/113538159661153615

**Comment by melroy89** [comment]
Can you reply one more time? I'm now for sure running the branch. Before it could have been still running on main.

**Comment by BentiGorlich** [comment]
The important part is you replying to me. Inbound federation was not changed :)

**Review by melroy89 — APPROVED** [review]

**Comment by melroy89** [comment]
> The important part is you replying to me. Inbound federation was not changed :)

I tried to reply again: https://kbin.melroy.org/m/random/p/186322/at-melroy-at-kbin-melroy-org-Here-is-a-test-toot-from-mastodon-for-you

**Comment by melroy89** [comment]
What about comments under threads??

**Comment by BentiGorlich** [comment]
Threads use the same `CreateHandler` so should also work fine

**Comment by melroy89** [comment]
Yup that also works: https://kbin.melroy.org/m/random/t/295162/Crane-on-a-plant and https://lemmy.world/post/16073167

**Comment by melroy89** [comment]
Like also works: https://wehavecookies.social/@BentiGorlich/113538353072337133/favourites

**Comment by BentiGorlich** [comment]
And the likes are also working :)

**Pull request merged**
