### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Mbin/Mbin](https://hosted.weblate.org/projects/mbin/kbin/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by melroy89** [comment]
You see..? it still has 8 commits, while 0 files are changed, because the commits are already in our `main` branch.. So weblate is not correctly syncing. I ask for official support now. https://mastodon.melroy.org/@melroy/111365445944249938

**Comment by e-five256** [comment]
I wonder if this is merged if it will think things are in sync again, or if it will just open another PR :thinking:

**Comment by melroy89** [comment]
> I wonder if this is merged if it will think things are in sync again
Done that/tried that already...

image

**Comment by melroy89** [comment]
@e-five256  I finally pressed "Reset all changes in the Weblate repository" in Weblate. That solved this endless loop...

**Pull request closed without merging**
