### PR TITLE
Revert "Translations update from Hosted Weblate"

### PR DESCRIPTION
**Pull request by nobodyatroot**
Reverts MbinOrg/mbin#404, @gregscoor see @e-five256's comment about variables in string translations.

### CODE REVIEW

**Comment by nobodyatroot** [comment]
The variables are also messed up in this version of the .yaml... maybe not worth reverting? @e-five256 what do you think? i'll close this is it's not worth it

**Comment by e-five256** [comment]
Yea, no need for a revert, we can try to fix it in weblate, I can try later tonight

**Comment by nobodyatroot** [comment]
Prior commit has problems, not reverting.

**Comment by e-five256** [comment]
Done in #408

**Pull request closed without merging**
