### PR TITLE
When editing an entry only use one type

### LINKED ISSUE #784: Can't edit Body field of posts with images
**Describe the bug**
No field with which to edit Body text on on posts with images

**On which Mbin instance did you find the bug?**
[kbin.melroy.org]

**Which Mbin version was running on the instance?**
[1.5.3]

**To Reproduce**
I'll be honest, I did not check all potential ways for this error to arise. I'd imagine this occurs on any kind of post with a photo, no matter which `Add new` button was used to make it happen, but I have no proof. The reproduction steps I provide below are the ones I do have proof for, or how I made the error arise myself. 

1. Click Add new link
2. Paste a link to an image in the URL field
3. Post your post
4. Try to edit your post

Or,
1. Go to an old post you made with an image
2. Try to edit your post

In both cases, there is no field for you to edit your Body text. Even if you have Body text in your post.

**Expected behavior**
There is a visible field for me to edit Body text.

**Smartphone (please complete the following information):**
 - Device: [iPhone 13 mini]
 - OS: [iOS 17.1.2]
 - Browser [stock browser, Safari]
 - Browser Version [17.1]

### PR DESCRIPTION
**Pull request by BentiGorlich**
- when editing an entry only use one type for the form in which all fields are accessible
- make the URL field editable

Closes #784, #861 and #463

### CODE REVIEW

**Comment by BentiGorlich** [comment]
Still some JS errors

**Comment by nobodyatroot** [comment]
the only thing that i can think of that may still be a source of confusion is on photo entry creation, there's no option to add body text:

image

although now maybe having these multiple options is redudant since you can still upload a photo in a normal thread entry:

image

**Comment by BentiGorlich** [comment]
> although now maybe having these multiple options is redudant since you can still upload a photo in a normal thread entry:

That has been the case for a while now... I was hesitant to change the way entries are created

> the only thing that i can think of that may still be a source of confusion is on photo entry creation, there's no option to add body text

That is true for the URL field as well... I think consolidating the create options should be done as well, but in a different PR

**Review by nobodyatroot — APPROVED** [review]

**Comment by nobodyatroot** [comment]
Yep, no need to explode this PR.

**Comment by TheVillageGuy** [comment]
> maybe just remove the photo entry option???

NOOO! Please don't

**Comment by MHLoppy** [comment]
> > maybe just remove the photo entry option???
> 
> NOOO! Please don't

This is late, but for what it's worth I think here we're just talking about removing the option in the submission selection type UI, not the functionality itself of actually uploading an image as part of a submission (which is of course pretty important to your use case with rimworld.gallery). You would just select one of the other two options and make a submission as usual!

**Comment by TheVillageGuy** [comment]
> This is late, but for what it's worth I think here we're just talking about removing the option in the submission selection type UI, not the functionality itself of actually uploading an image as part of a submission (which is of course pretty important to your use case with rimworld.gallery). You would just select one of the other two options and make a submission as usual!

As long as it's possible to set a magazine to images only, I don't want people uploading text threads or links on /m/RimWorldPorn it will be a moderation nightmare

**Comment by MHLoppy** [comment]
Per-magazine submission restrictions sounds like a good feature request!

**Comment by TheVillageGuy** [comment]
It can't be enforced on other instances yet though, although that could be solved by some sort of auto moderation on the home server of the magazine.

**Pull request merged**
