### PR TITLE
Update js packages

### PR DESCRIPTION
**Pull request by melroy89**
Update minor & major releases of all JS packages (except chart.js to avoid regression as far as I could remember).

### CODE REVIEW

**Comment by asdfzdfj** [comment]
applied to my instance and didn't see any obvious problems, although it looks like `npm` really wants to update chart.js in `package-lock.json` like this after running `npm i`:

```diff
diff --git a/package-lock.json b/package-lock.json
index 5cad4fb3..42649fce 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -16,7 +16,7 @@
                 "@symfony/ux-autocomplete": "file:vendor/symfony/ux-autocomplete/assets",
                 "@symfony/ux-chartjs": "file:vendor/symfony/ux-chartjs/assets",
                 "@symfony/webpack-encore": "^4.5.0",
-                "chart.js": "^3.8.2",
+                "chart.js": "^3.8.0 <3.9",
                 "core-js": "^3.34.0",
                 "file-loader": "^6.2.0",
                 "glightbox": "^3.2.0",
```

**Comment by melroy89** [comment]
> applied to my instance and didn't see any obvious problems, although it looks like `npm` really wants to update chart.js in `package-lock.json` like this after running `npm i`:
> 
> ```diff
> diff --git a/package-lock.json b/package-lock.json
> index 5cad4fb3..42649fce 100644
> --- a/package-lock.json
> +++ b/package-lock.json
> @@ -16,7 +16,7 @@
>                  "@symfony/ux-autocomplete": "file:vendor/symfony/ux-autocomplete/assets",
>                  "@symfony/ux-chartjs": "file:vendor/symfony/ux-chartjs/assets",
>                  "@symfony/webpack-encore": "^4.5.0",
> -                "chart.js": "^3.8.2",
> +                "chart.js": "^3.8.0 <3.9",
>                  "core-js": "^3.34.0",
>                  "file-loader": "^6.2.0",
>                  "glightbox": "^3.2.0",
> ```

As long as the chartjs version doesn't exceeds 3.9 it should be fine. What is the version of chartjs npm installed? Or want to install?

**Comment by asdfzdfj** [comment]
it does seem to install version 3.8.2, it's probably fine. it's just that I find the act of running `npm i` and then have a git unstaged changes just from that a bit odd.

now that I look at it again it looks like it attempt to sync version in from `package.json` to the lockfile (it specified `"chart.js": "^3.8.0 <3.9"`, just like in the diff I got)

```
kbin % npm ls chart.js
kbin@ /usr/local/www/kbin
├─┬ @symfony/ux-chartjs@1.1.0 -> ./vendor/symfony/ux-chartjs/assets
│ └── chart.js@3.8.2 deduped
└── chart.js@3.8.2
```

**Comment by melroy89** [comment]
> it does seem to install version 3.8.2, it's probably fine. it's just that I find the act of running `npm i` and then have a dirty git workspace from that a bit odd.
> 
> now that I look at it again it looks like it attempt to sync version in from `package.json` to the lockfile (it specified `"chart.js": "^3.8.0 <3.9"`, just like in the diff I got)
> 
> ```
> kbin % npm ls chart.js
> kbin@ /usr/local/www/kbin
> ├─┬ @symfony/ux-chartjs@1.1.0 -> ./vendor/symfony/ux-chartjs/assets
> │ └── chart.js@3.8.2 deduped
> └── chart.js@3.8.2
> 
> kbin % rg chart\\.js package*.json
> package.json
> 17:        "chart.js": "^3.8.0 <3.9",
> 
> package-lock.json
> 19:                "chart.js": "^3.8.2",
> ```

Yes, this is totally fine. See also the command: `npm list` to show you the current installed packages + versions.

**Review by asdfzdfj — APPROVED** [review]
yeah I tried again after update and it's good now

**Pull request merged**
