### PR TITLE
Add field to all content response DTOs: `canAuthUserModerate`

### PR DESCRIPTION
**Pull request by BentiGorlich**
- All content response DTOs (entry, entry_comment, post, post_comment) now have a field `canLoggedInUserModerate` which indicates whether the loggedin user can moderate said content

Link #1001

### CODE REVIEW

**Comment by jwr1** [comment]
Just a tiny change, but would you be able to change the field name to `canAuthUserModerate` (can authenticated user moderate)? It's not too big a deal, but IMO, it sounds better than `canLoggedInUserModerate`. If you think it sounds better as it is, feel free to leave it alone though.

**Comment by BentiGorlich** [comment]
done

**Review by jwr1 — CHANGES_REQUESTED** [review]
I just tested it out, and it looks like `canAuthUserModerate` is null if it's not a first level comment. Here's an example you can look at (comments I can mod have "CAN MOD" next to them, it should be all of them though):

image

**Comment by BentiGorlich** [comment]
I updated the PR :)

**Comment by jwr1** [comment]
It looks like it is fixed for entry comments, but the issue still exists with post (microblog) comments.

**Comment by BentiGorlich** [comment]
True, forgot about that. I will add it tomorrow

Am 19. August 2024 22:55:46 MESZ schrieb John Wesley ***@***.***>:

**Comment by BentiGorlich** [comment]
Done

**Review by jwr1 — APPROVED** [review]
Just tried this also, looks good to me!

**Pull request merged**
