### PR TITLE
Ran compose recipes + Move to NPM + port 8008 (Part 6)

### PR DESCRIPTION
**Pull request by melroy89**
- Clean-up clover.xml file (should have never been checked in the first place)
- Move from Yarn to NPM (See Webpack Encore PR: https://github.com/symfony/recipes/pull/1229)
    - Indirectly also updates all NodeJS packages to the latest version
- I dare to run the recipe `symfony/webpack-encore-bundle` as well as `doctrine/doctrine-bundle` this time, but:
    - I confirmed a [regression in Doctrine](https://github.com/doctrine/orm/pull/10455) with the `report_fields_where_declared` setting. Which is used to switch to a "new mapping driver mode as of Doctrine ORM 2.16", that breaks class inheritance with the separate sequence generator table we use for the child classes of the `Vote` class. Anyhow, this option needs to be set to `false` (do **not** opt-in). See also: https://github.com/doctrine/orm/issues/10953
- Update Docker locally mapped port from 80 to port 8008 (~~BOOB~~ 🔒 )

### CODE REVIEW

**Comment by e-five256** [comment]
I'm having issues building docker for this with

```
 => ERROR [messenger_ap builder-nodejs 9/9] RUN npm run build                                                                                                                                                                            0.8s
------
 > [messenger_ap builder-nodejs 9/9] RUN npm run build:
0.743 
0.743 > build
0.743 > encore production --progress
0.743 
0.747 sh: encore: not found
------
failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 127
```

**Comment by melroy89** [comment]
> I'm having issues building docker for this with
> 
> ```
>  => ERROR [messenger_ap builder-nodejs 9/9] RUN npm run build                                                                                                                                                                            0.8s
> ------
>  > [messenger_ap builder-nodejs 9/9] RUN npm run build:
> 0.743 
> 0.743 > build
> 0.743 > encore production --progress
> 0.743 
> 0.747 sh: encore: not found
> ------
> failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 127
> ```

Sorry about that, I tested it earlier but I added NODE_ENV=production later I think. Anyhow, I include `--include=dev` now. I did the same on other places just to be sure. And also execute a `npm run build` with production flag on `post-upgrade` script.

**Review by e-five256 — APPROVED** [review]
this builds for my local dev env, and I didn't notice any issues, but I'm not as knowledgeable compared to my peers so not sure if you want a second opinion just to be cautious, since it seems like a pretty big change. I also think it's a good idea to communicate maybe in general once merged as a heads up that the www container port on the host changed if people need to repoint things to it

**Comment by nobodyatroot** [comment]
It looks like we don't need to use `node:lts-alpine` image to support whatever was broken with `yarn`, the latest release of `node:alpine` works fine now. I doubled check that and all these changes on a docker dev instance with db test fixtures, everything still seems to work fine.

**Review by nobodyatroot — CHANGES_REQUESTED** [review]
`Dockerfile` request, line `68`

Change:

`FROM node:lts-alpine as builder-nodejs`

To:

 `FROM node:alpine as builder-nodejs`

**Review by nobodyatroot — APPROVED** [review]

**Review by e-five256 — APPROVED** [review]

**Comment by melroy89** [comment]
Thanks for the improvement @nobodyatroot

**Pull request merged**
