### PR TITLE
Introducing a Project Info service (updates useragent version as well)

### PR DESCRIPTION
**Pull request by melroy89**
- Introduce a Project Info service
- Use this service to also update the user-agent string version (iso of `0.1`)

### CODE REVIEW

**Review by nobodyatroot — DISMISSED** [review]
Looks good to me!

**Comment by melroy89** [comment]
> Looks good to me!

Except I missed `this` ;)

**Comment by nobodyatroot** [comment]
> > Looks good to me!
> 
> Except I missed `this` ;)

Eh, minor detail. :-P

**Comment by melroy89** [comment]
U sure now ;P?

**Pull request merged**
