### PR TITLE
Supporting different actor types as User + Improved actor checking

### PR DESCRIPTION
**Pull request by melroy89**
1. Support more than just "Person" as actor type. Support the following User actor types from AP:
    - Person
    - Service (== Bot Account in Lemmy, which Mbin now will also support)
image

    - Organization
    - Application

2. Furthermore, I extend the code with additional empty / null or undefined checks of actor. Which I also saw in the past year popping-up in consumer job logging. 
3. Add additional documentation in the code. Please document your code!
4. DB migration is created to add the type of the user/actor in the PostgreSQL database.
5. AP code to actually use the actor type info and insert the correct value into the type field (as well as getting the user type from the DB).
6. Support `application/json` for AP calls
7. Change instance actor name to Mbin
8. Last but not least, updating composer packages and running PHPUnit bridge recipe (preparing for unit-testing).

Spec: https://www.w3.org/TR/activitystreams-vocabulary/#actor-types

Related Mastodon PR: https://github.com/mastodon/mastodon/pull/6997/files

### CODE REVIEW

**Comment by melroy89** [comment]
Should we maybe add `Organization` as a user as well?

**Comment by nobodyatroot** [comment]
It probably wouldn't hurt to add `Organization` as well as `Application` since a bot could be an "application", no? It looks like the Mastodon PR covers all 4 in `app/services/resolve_url_service.rb`. Then we'd have all types covered even if we're not doing anything special with them.

**Comment by melroy89** [comment]
> It probably wouldn't hurt to add `Organization` as well as `Application` since a bot could be an "application", no? It looks like the Mastodon PR covers all 4 in `app/services/resolve_url_service.rb`. Then we'd have all types covered even if we're not doing anything special with them.

Looks like it.. Mbin only uses Groups as "Magazines", so we definitely do not want to include Groups for users haha.

**Comment by melroy89** [comment]
I would like add some unit-test but I got some issues with stubbing/mocking some doctine classes, which is not cool... 

I want to split the PR now, otherwise it becomes too complex. But I updated the PHP packages and run the PhpUnit bridge composer recipe.

**Review by nobodyatroot — APPROVED** [review]
I ran this branch in my test environment across 3 locally federated instances and on [kbin.run](kbin.run) for a little bit now and I don't see any issues with federation, looks good to me.

**Comment by melroy89** [comment]
> I ran this branch in my test environment across 3 locally federated instances and on [kbin.run](https://kbin.run/) for a little bit now and I don't see any issues with federation, looks good to me.

Thanks great. I will run it at of the day on my instance as well for a little while. And then merge it most likely. Thanks for the approval.

**Comment by melroy89** [comment]
I think a follow-up for this PR would be to make a "Service" user as "Bot" in Mbin.

**Comment by melroy89** [comment]
OK done.. actor type is correctly fetched and inserted (and updated) into the database. I didn't change UserDTO nor the API. Although the API isn't used yet by any app.

I did drop the `is_bot` column from the user table, to avoid duplicated data. And various other improvements.

**Comment by melroy89** [comment]
I would like to get these debugging somehow:

```
[2023-10-20T01:12:49.435246+00:00] php.WARNING: Warning: Undefined array key "type" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"type\" at /var/www/kbin.melroy.org/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2923)"} []
[2023-10-20T01:12:49.449637+00:00] php.WARNING: Warning: Undefined array key "type" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"type\" at /var/www/kbin.melroy.org/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2923)"} []
[2023-10-20T01:12:49.586018+00:00] php.WARNING: Warning: Undefined array key "type" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"type\" at /var/www/kbin.melroy.org/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2923)"} []
[2023-10-20T01:12:50.583686+00:00] php.WARNING: Warning: Undefined array key "type" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"type\" at /var/www/kbin.melroy.org/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2923)"} []
[2023-10-20T01:12:52.457273+00:00] php.WARNING: Warning: Trying to access array offset on value of type null {"exception":"[object] (ErrorException(code: 0): Warning: Trying to access array offset on value of type null at /var/www/kbin.melroy.org/html/src/Service/ActivityPubManager.php:127)"} []
[2023-10-20T01:12:52.457395+00:00] php.WARNING: Warning: Trying to access array offset on value of type null {"exception":"[object] (ErrorException(code: 0): Warning: Trying to access array offset on value of type null at /var/www/kbin.melroy.org/html/src/Service/ActivityPubManager.php:145)"} []
[2023-10-20T01:12:52.493066+00:00] php.WARNING: Warning: Undefined array key "type" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"type\" at /var/www/kbin.melroy.org/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2923)"} []
[2023-10-20T01:12:55.282261+00:00] php.WARNING: Warning: Undefined array key "avatar" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"avatar\" at /var/www/kbin.melroy.org/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2571)"} []
[2023-10-20T01:12:55.890215+00:00] php.WARNING: Warning: Undefined array key "type" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"type\" at /var/www/kbin.melroy.org/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2923)"} []
[2023-10-20T01:12:59.315351+00:00] php.WARNING: Warning: Undefined array key "type" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"type\" at /var/www/kbin.melroy.org/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2923)"} []
[2023-10-20T01:13:04.273555+00:00] php.WARNING: Warning: Undefined array key "avatar" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"avatar\" at /var/www/kbin.melroy.org/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2571)"} []
[2023-10-20T01:13:05.283597+00:00] php.WARNING: Warning: Trying to access array offset on value of type null {"exception":"[object] (ErrorException(code: 0): Warning: Trying to access array offset on value of type null at /var/www/kbin.melroy.org/html/src/Service/ActivityPubManager.php:127)"} []
[2023-10-20T01:13:05.283725+00:00] php.WARNING: Warning: Trying to access array offset on value of type null {"exception":"[object] (ErrorException(code: 0): Warning: Trying to access array offset on value of type null at /var/www/kbin.melroy.org/html/src/Service/ActivityPubManager.php:145)"} []
[2023-10-20T01:13:08.305940+00:00] php.WARNING: Warning: Undefined array key "type" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"type\" at /var/www/kbin.melroy.org/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2923)"} []
[2023-10-20T01:13:12.442395+00:00] php.WARNING: Warning: Undefined array key "type" {"exception":"[object] (ErrorException(code: 0): Warning: Undefined array key \"type\" at /var/www/kbin.melroy.org/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2923)"} []
```

**Review by nobodyatroot — APPROVED** [review]
I haven't observed any instability or issues running this branch on my prod instance, I don't see any reason not to approve it. Any further improvements can be addressed with a new issue/PR. Good job!

**Pull request merged**
