### PR TITLE
1 letter change lol

### PR DESCRIPTION
**Pull request by melroy89**
Just make the name start with a capital letter in the footer, making it consistent across the rest of the template/code/documentation.

### CODE REVIEW

**Review by simonrcodrington — APPROVED** [review]
A solid improvement 🦙

**Comment by melroy89** [comment]
Ship it!

**Review by nobodyatroot — COMMENTED** [review]
Nope, can't approve. Too many changes, sorry! jk... approved.

**Comment by melroy89** [comment]
> Nope, can't approve. Too many changes, sorry! jk... approved.

too late mate.

**Comment by nobodyatroot** [comment]
i noticed, you guys are too damn fast!

**Comment by melroy89** [comment]
> i noticed, you guys are too damn fast!

glassfiber

**Pull request merged**
