### PR TITLE
WIP Implement downvote modes

### LINKED ISSUE #482: Make downvotes optional
Add a variable in the `.env` file to entirely disable dislikes. This requires the frontend to remove the downvote buttons and the controllers to check whether they are allowed to add a downvote

### PR DESCRIPTION
**Pull request by thepaperpilot**
This is a WIP PR, but I've been struggling to find time to complete it. Really it's down to just testing to make sure it works everywhere and that I didn't miss any API endpoints or anything. I'm also wondering if there's anything we should do to communicate to other servers if we support downvotes or not (I don't think AP has a standard for that though - perhaps something to discuss with the lemmy devs?)

I'd appreciate help from the community to get this PR ready to merge, if possible. I believe there was also an issue with it not loading the setting correctly from the DB, but my dev environment isn't playing nice so I can't even look at that right now (but I'll try to restore my dev environment when I do have time).

Closes #482

### CODE REVIEW

**Comment by asdfzdfj** [comment]
Can I get some description on what the problem is and what your plan/solution/goal for this is?

while I can sort of guess what it's supposed to do (add 3 modes of handling dislikes: process as normal, process but don't show, discards them entirely), but having a concrete description/spec/goal would help greatly in getting it working, and also avoids misunderstanding on what the goals are for other contributors

---

> if there's anything we should do to communicate to other servers if we support downvotes or not

as for that, I think a good place to start would be to add this info as a [nodeinfo](https://github.com/jhass/nodeinfo/issues) `metadata` field, and discuss these new fields with lemmy _and_ other threadiverse implementors that use dislikes for an agreement in field name and meaning/semantics

perhaps it could look like this:

```jsonc
{
  // ...
  "metadata": {
    // whether the instance process Dislikes (downvotes) at all
    "enableDislike": true,
    // whether the instance is willing to disclose/publish known dislikes, possibly optional
    "publishDislike": true,
  }
}
```

**Comment by e-five256** [comment]
Just for a bit of context, I had mentioned trying to assist with this (but think your clarifying questions are useful and don't want to answer in @thepaperpilot's place if there's time)

**Comment by thepaperpilot** [comment]
As for the inter-server communication about the handling, I just realized it'd probably make sense to keep it open enough for future implementations that are more finely grained to work. In theory, communities or even individual thread creators might want to disable downvotes without affecting the rest of the site.

**Comment by BentiGorlich** [comment]
I am guessing that I will close this PR, as I cannot push to the branch of thepaperpilots repo. So I'll create a new branch in our repo and make a PR for it

**Comment by thepaperpilot** [comment]
> I am guessing that I will close this PR, as I cannot push to the branch of thepaperpilots repo. So I'll create a new branch in our repo and make a PR for it

When you do, can you mention this pr or link to the new one here? I'd like to follow it

**Comment by BentiGorlich** [comment]
Of course. I wouldn't use your code without linking back to you :)

**Comment by BentiGorlich** [comment]
Closed in favor of #1022

**Pull request closed without merging**
