### PR TITLE
Updated sass code

### LINKED ISSUE #1319: Webpack/Sass warnings
I may take care of this on my own later, but as long as I haven't assigned it to myself, anyone else can feel free to take it.

```
 warn  in ./assets/styles/app.scss

Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 0, column 8 of file:///workspaces/mbin/assets/styles/app.scss:0:8:
Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

0 | @import '@fortawesome/fontawesome-free/scss/fontawesome';


assets/styles/app.scss 1:9  root stylesheet


 warn  in ./assets/styles/app.scss

Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 1, column 8 of file:///workspaces/mbin/assets/styles/app.scss:1:8:
Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

1 | @import '@fortawesome/fontawesome-free/scss/solid';


assets/styles/app.scss 2:9  root stylesheet


 warn  in ./assets/styles/app.scss

Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 2, column 8 of file:///workspaces/mbin/assets/styles/app.scss:2:8:
Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

2 | @import '@fortawesome/fontawesome-free/scss/brands';


assets/styles/app.scss 3:9  root stylesheet


 warn  in ./assets/styles/app.scss

Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 3, column 8 of file:///workspaces/mbin/assets/styles/app.scss:3:8:
Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

3 | @import 'simple-icons-font/font/simple-icons';


assets/styles/app.scss 4:9  root stylesheet


 warn  in ./assets/styles/app.scss

Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 5, column 8 of file:///workspaces/mbin/assets/styles/app.scss:5:8:
Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

5 | @import 'mixins/animations';


assets/styles/app.scss 6:9  root stylesheet


 warn  in ./assets/styles/app.scss

Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 8, column 26 of file:///workspaces/mbin/node_modules/@fortawesome/fontawesome-free/scss/_icons.scss:8:26:
Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
Use string.unquote instead.

More info and automated migrator: https://sass-lang.com/d/import

8 |     #{$fa-icon-property}: unquote("\"#{ $icon }\"");


node_modules/@fortawesome/fontawesome-free/scss/_icons.scss 9:27       @import
node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss 20:9  @import
assets/styles/app.scss 1:9                                             root stylesheet


 warn  in ./assets/styles/app.scss

Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 18, column 85 of file:///workspaces/mbin/assets/styles/layout/_breakpoints.scss:18:85:
Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
Use map.keys instead.

More info and automated migrator: https://sass-lang.com/d/import

18 | @function breakpoint-next($name, $breakpoints: $grid-breakpoints, $breakpoint-names: map-keys($breakpoints)) {


assets/styles/layout/_breakpoints.scss 19:86   breakpoint-next()
assets/styles/layout/_breakpoints.scss 113:12  media-breakpoint-only()
assets/styles/components/_sidebar.scss 97:7    @import
assets/styles/app.scss 27:9                    root stylesheet


 warn  in ./assets/styles/app.scss

Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 28, column 54 of file:///workspaces/mbin/node_modules/@fortawesome/fontawesome-free/scss/brands.scss:28:54:
Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
Use string.unquote instead.

More info and automated migrator: https://sass-lang.com/d/import

28 |   .#{$fa-css-prefix}-#{$name} { #{$fa-icon-property}: unquote("\"#{ $icon }\""); }


node_modules/@fortawesome/fontawesome-free/scss/brands.scss 29:55  @import
assets/styles/app.scss 3:9                                         root stylesheet


 warn  in ./assets/styles/app.scss

Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 31, column 10 of file:///workspaces/mbin/assets/styles/layout/_breakpoints.scss:31:10:
Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
Use map.get instead.

More info and automated migrator: https://sass-lang.com/d/import

31 |     $min: map-get($breakpoints, $name);


assets/styles/layout/_breakpoints.scss 32:11  breakpoint-min()
assets/styles/layout/_breakpoints.scss 64:11  media-breakpoint-up()
assets/styles/layout/_layout.scss 18:3        @import
assets/styles/app.scss 16:9                   root stylesheet


 warn  in ./assets/styles/app.scss

Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 45, column 10 of file:///workspaces/mbin/assets/styles/layout/_breakpoints.scss:45:10:
Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
Use map.get instead.

More info and automated migrator: https://sass-lang.com/d/import

45 |     $max: map-get($breakpoints, $name);


assets/styles/layout/_breakpoints.scss 46:11  breakpoint-max()
assets/styles/layout/_breakpoints.scss 77:11  media-breakpoint-down()
assets/styles/layout/_breakpoints.scss 133:5  @import
assets/styles/app.scss 14:9                   root stylesheet
```

### PR DESCRIPTION
**Pull request by garrettw**
changed `@import` to `@use` and fixed everything that affected

See: https://sass-lang.com/d/import

Webpack does build successfully, and the only Sass warnings now are from upstream (fontawesome).

Fixes #1319

### CODE REVIEW

**Comment by melroy89** [comment]
I also notice these warnings after updating webpack. I didn't know how to solve it. Luckily you do :)

**Review by melroy89 — APPROVED** [review]

**Comment by garrettw** [comment]
@melroy89 would you be able to test this branch out and verify that no CSS is broken on the front end? Or anyone else for that matter?

Or if I’m able to fully test it myself before anyone else does, I’ll let you know here.

**Comment by melroy89** [comment]
Sure I can test it on kbin.melroy.org. There is a small merge conflict though with webpack config file.

**Comment by garrettw** [comment]
I see that now. I’m not near a computer right now so if you want to fix it before I do, feel free. Without seeing what the exact conflict is, I think the correct resolution should be to just rename the file in this branch to `.cjs`.

**Comment by melroy89** [comment]
I see, I fixed it myself :)

**Comment by melroy89** [comment]
And... it's running live at: https://kbin.melroy.org now.

With the following warnings left:

```sh
99% done plugins FriendlyErrorsWebpackPlugin WARN  Compiled with 8 warnings                                                                                                                                                                          9:44:19 PM

 warn  in ./assets/styles/app.scss                                                                                                                                                                       9:44:19 PM

Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 8, column 8 of file:///var/www/kbin.melroy.org/html/node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss:8:8:
Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

8 | @import 'functions';


node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss 9:9  @use
assets/styles/app.scss 1:1                                            root stylesheet


 warn  in ./assets/styles/app.scss                                                                                                                                                                       9:44:19 PM

Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 8, column 26 of file:///var/www/kbin.melroy.org/html/node_modules/@fortawesome/fontawesome-free/scss/_icons.scss:8:26:
Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
Use string.unquote instead.

More info and automated migrator: https://sass-lang.com/d/import

8 |     #{$fa-icon-property}: unquote("\"#{ $icon }\"");


node_modules/@fortawesome/fontawesome-free/scss/_icons.scss 9:27       @import
node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss 20:9  @use
assets/styles/app.scss 1:1                                             root stylesheet


 warn  in ./assets/styles/app.scss                                                                                                                                                                       9:44:19 PM

Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 9, column 8 of file:///var/www/kbin.melroy.org/html/node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss:9:8:
Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

9 | @import 'variables';


node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss 10:9  @use
assets/styles/app.scss 1:1                                             root stylesheet


 warn  in ./assets/styles/app.scss                                                                                                                                                                       9:44:19 PM

Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 10, column 8 of file:///var/www/kbin.melroy.org/html/node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss:10:8:
Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

10 | @import 'mixins';


node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss 11:9  @use
assets/styles/app.scss 1:1                                             root stylesheet


 warn  in ./assets/styles/app.scss                                                                                                                                                                       9:44:19 PM

Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 11, column 8 of file:///var/www/kbin.melroy.org/html/node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss:11:8:
Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

11 | @import 'core';


node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss 12:9  @use
assets/styles/app.scss 1:1                                             root stylesheet


 warn  in ./assets/styles/app.scss                                                                                                                                                                       9:44:19 PM

Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 12, column 8 of file:///var/www/kbin.melroy.org/html/node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss:12:8:
Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

12 | @import 'sizing';


node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss 13:9  @use
assets/styles/app.scss 1:1                                             root stylesheet


 warn  in ./assets/styles/app.scss                                                                                                                                                                       9:44:19 PM

Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 28, column 54 of file:///var/www/kbin.melroy.org/html/node_modules/@fortawesome/fontawesome-free/scss/brands.scss:28:54:
Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
Use string.unquote instead.

More info and automated migrator: https://sass-lang.com/d/import

28 |   .#{$fa-css-prefix}-#{$name} { #{$fa-icon-property}: unquote("\"#{ $icon }\""); }


node_modules/@fortawesome/fontawesome-free/scss/brands.scss 29:55  @use
assets/styles/app.scss 3:1                                         root stylesheet


 warn  in ./assets/styles/app.scss                                                                                                                                                                       9:44:19 PM

Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
12 repetitive deprecation warnings omitted.
Run in verbose mode to see all warnings.
```

But most likely we won't be able to fix these yourselves.

**Comment by melroy89** [comment]
On the federation page, the 'badges' for each domain seems to be broken:

image

**Comment by garrettw** [comment]
Got it, thanks for the feedback. Feel free to rollback prod and I’ll take a look at fixing this soon.

**Comment by melroy89** [comment]
I actually do expect you test your changes 😆 .. Sorry that I approved and let it merge. Please, next time validate your changes yourself as well.

**Comment by garrettw** [comment]
Sorry about that, I thought I had. Guess I didn’t look in enough places.

**Review by melroy89 — APPROVED** [review]
I also tested this PR, this now seems to work fine as well.

**Pull request merged**
