### PR TITLE
Redesign federation page

### PR DESCRIPTION
**Pull request by BentiGorlich**
- 3 different sections
- TOC
- always show panels with an empty notice when there are no entries

grafik

### CODE REVIEW

**Review by melroy89 — APPROVED** [review]
Thank you!

**Comment by melroy89** [comment]
Hopefully an update like this `merge branch main into..` will not remove the approval?

**Comment by BentiGorlich** [comment]
@melroy89 
> The base branch requires all commits to be signed

**Comment by melroy89** [comment]
> @melroy89
> 
> > The base branch requires all commits to be signed

yea nice right..? I also try to enable that while I was there.. Not a good idea?

image

**Comment by melroy89** [comment]
> > @melroy89
> > > The base branch requires all commits to be signed
> 
> yea nice right..? I also try to enable that while I was there.. Not a good idea?
> 
> image
> 
> So your first commit doesn't seems to be signed:
> 
> image

I guess I will disable this again.. but maybe a good thing to also enable soon...

**Comment by BentiGorlich** [comment]
I just setup gpg signing on my end. Maybe in the future. I think this is a good idea in general. Don't know if it is necessary

**Pull request merged**
