### PR TITLE
Only do an update actor if it is actually necessary

### PR DESCRIPTION
**Pull request by BentiGorlich**
This has an enourmous impact. In the Activity Handler we dispatch an `UpdateActorMessage` every time an Activity comes on for a user which has not been fetched for an hour or two. If the server is down for a bit we end up with an enourmus amount of these messages. Now we didn't check if we actually need to update an actor in the Handler for the message. This PR adds that

### CODE REVIEW

**Review by nobodyatroot — APPROVED** [review]

**Comment by e-five256** [comment]
is `apFetchedAt` ever `null` coming into this? like on first fetch?

**Comment by BentiGorlich** [comment]
> is `apFetchedAt` ever `null` coming into this? like on first fetch?

could be :thinking:

**Comment by BentiGorlich** [comment]
would still be working though

**Comment by BentiGorlich** [comment]
grafik

**Review by e-five256 — APPROVED** [review]

**Pull request merged**
