### PR TITLE
Restyle login/register social and action button sections

### PR DESCRIPTION
**Pull request by e-five256**
Based on the feedback @TheVillageGuy gave in #642 and #643

- make buttons full form width
- make social buttons larger and more grid/flex based
  - 1 social login = full width
  - mobile = full width
- make social buttons appear before actions
  - on login page social login now appears before register links
  - on register page social register now appears before login links
- add line separators that only show up if there are elements (no social login = no separator, same for register/login links)
- social buttons on reset password form have been removed, passwords on our side aren't involved in regards to SSO
- add new admin option to place social buttons above native login/registration forms
image

<details> 
<summary>Comparison screenshots</summary>

|before|after|
|-|-|
| login all social
|image|image|
| login mobile
|image|image|
| login 1 social
|image|image|
| login 0 social
|image|image|
| login social first
||image|
| login sso mode 2 socials
|image|image|
| register all social
|image|image|
| register mobile
|image|image|
| register 1 social
|image|image|
| register 0 social
|image|image|
| register social first
||image|
| register disabled
|image|image|
| reset password all social
| (reminder socials were just straight up removed in after)
|image|image|
| reset password 1 social
|image|image|
| reset password 0 social
|image|image|
| resend account activation email
|image|image|

</details>

### CODE REVIEW

**Comment by TheVillageGuy** [comment]
That's great! I'd like to see some kind of indicator to draw attention to the fact that it's possible to use the socials as well, as people with little computer knowledge do not make the association when just seeing these buttons and simply either refrain from login in/registering or start filling in the form. I understand my layout on RimWorld.gallery is not very good looking but it's super clear that Google can be used to log in. Some kind of compromise would be appreciated

**Comment by e-five256** [comment]
Would an admin option of the social buttons appearing before login/register form fill your criteria?

I also realized going through this reset password form is shown when in SSO only mode, so potentially will make that redirect to login similar to register does, as part of this

**Comment by TheVillageGuy** [comment]
Yes, with perhaps a fancy line above it 'log/sign in using'

**Comment by nobodyatroot** [comment]
@TheVillageGuy can we close https://github.com/MbinOrg/mbin/pull/642 and https://github.com/MbinOrg/mbin/pull/643 in favor of this PR instead (once @e-five256 has a chance to finish the work, no rush of course)?

**Comment by TheVillageGuy** [comment]
Yes and done

**Comment by BentiGorlich** [comment]
Man this looks good. What is the draft part about this?

**Comment by e-five256** [comment]
I need #740 to make the separator not look show up when SSO only mode is enabled (easier than trying to do CSS thats like `:not before <form>, :not after <form>`

I should be able to get this fixed up this weekend

I also found the full width buttons a little bad looking. I changed that to like 50% width on desktop and 100% on mobile. I'm trying to think of names for the classes, that's the hard part. I'd like to extend that kind of styling to many other forms like saving your profile information or saving the admin page settings because I think it makes it much easier to see/click on

**Comment by e-five256** [comment]
I've updated the description/screenshots for the current state of things

**Review by nobodyatroot — APPROVED** [review]
LGTM, massive improvement

**Review by melroy89 — APPROVED** [review]

**Pull request merged**
