### PR TITLE
enable auto rotate filter when making thumbnail

### PR DESCRIPTION
**Pull request by asdfzdfj**
enable auto rotate filter to properly make thumbnails for images that have rotation data stored in exif, such as those coming from phones.

note that this required php exif extension for it to work (added extension in docker build, basic php install for bare metal guide should already included exif extension)

### CODE REVIEW

**Comment by melroy89** [comment]
> php install for bare metal guide should already included exif extension

Does it? Guide says:

> php8.2-common php8.2-fpm php8.2-cli php8.2-amqp php8.2-pgsql php8.2-gd php8.2-curl php8.2-simplexml php8.2-dom php8.2-xml php8.2-redis php8.2-mbstring php8.2-intl

**Comment by asdfzdfj** [comment]
> > php install for bare metal guide should already included exif extension
> 
> Does it? Guide says:
> 
> > php8.2-common php8.2-fpm php8.2-cli php8.2-amqp php8.2-pgsql php8.2-gd php8.2-curl php8.2-simplexml php8.2-dom php8.2-xml php8.2-redis php8.2-mbstring php8.2-intl

it should be covered by `php8.2-common`

**Comment by nobodyatroot** [comment]
Maybe a different PR, but it would also be good a time to get that "security" feature included into the exif processing where all the location metadata (and anything else deemed PII) is stripped out.

**Comment by melroy89** [comment]
@asdfzdfj Nice ok. I have just only one favor to ask. Due to file conflicts. Could the regression PR be merged earlier than this one? https://github.com/MbinOrg/mbin/pull/108

**Comment by asdfzdfj** [comment]
> @asdfzdfj Nice ok. I have just only one favor to ask. Due to file conflicts. Could the regression PR be merged earlier than this one? #108

want to merge #108 first? alright

---

> Maybe a different PR, but it would also be good a time to get that "security" feature included into the exif processing where all the location metadata (and anything else deemed PII) is stripped out.

I do have [something](https://github.com/asdfzdfj/mbin/tree/new/image-exif-scrubber) in the works regarding image exif cleaning (`exiftool` based), perhaps I should open a new draft PR about this, for I could use some help on how and where to plug this processing in.

**Comment by melroy89** [comment]
OK the regression is resolved and PR #108 is indeed merged now. sorry for the merge conflict. But Mbin has at least a working up/down vote and boost again.

**Review by nobodyatroot — APPROVED** [review]

**Pull request merged**
