### PR TITLE
Add db optimization migration

### PR DESCRIPTION
**Pull request by nobodyatroot**
Sync with recent /kbin commit/observations to improve db performance in large scale production environment.

### CODE REVIEW

**Review by e-five256 — DISMISSED** [review]

**Comment by BentiGorlich** [comment]
I really am no pSQL wizard especially when it comes to tuning it. I'd say when you have it running on your instance and there are no problems this is fine...

**Comment by nobodyatroot** [comment]
> I really am no pSQL wizard especially when it comes to tuning it. I'd say when you have it running on your instance and there are no problems this is fine...

Neither am I, but so far so good. This has been running live for ~12 hours now without issue.

**Review by BentiGorlich — APPROVED** [review]

**Comment by melroy89** [comment]
I now see unamed indexes? 

image

And doctrine is not in sync.. If you want to add a new index, you should try to rely on ORM Doctrine. Eg. add `#[Index(columns: ['ap_profile_id'], name: 'user_ap_profile_id_idx')]` in case of an index to the table in PHP like so (EXAMPLE):

```php
#[Index(columns: ['visibility'], name: 'user_visibility_idx')]
#[Index(columns: ['ap_id'], name: 'user_ap_id_idx')]
#[Index(columns: ['ap_profile_id'], name: 'user_ap_profile_id_idx')]
class User implements UserInterface, PasswordAuthenticatedUserInterface, VisibilityInterface, TwoFactorInterface, BackupCodeInterface, EquatableInterface, ActivityPubActorInterface, ApiResourceInterface
```

Or add a unique field via: ` #[Column(type: 'string', unique: true, nullable: false)]` again in PHP.


Then generate a new migration file via `php bin/console doctrine:migrations:diff`. 

More info: https://symfony.com/bundles/DoctrineMigrationsBundle/current/index.html#generating-migrations-automatically

**Comment by melroy89** [comment]
> I now see empty columns for the new indices

Maybe it's just Adminer after all.. Stupid UI tool.

**Pull request merged**
