### PR TITLE
Improve invalid CSRF token logging + add explicit dependency

### PR DESCRIPTION
**Pull request by melroy89**
Small improvements:

- Add `$id` to invalid CSRF error message. So we know which ID is causing the issue.
- Add missing `symfony/security-csrf` explict dependency

### CODE REVIEW

**Comment by melroy89** [comment]
ow.. I got finally something in my log (after a long time of waiting):

```json
{"message":"Uncaught PHP Exception Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException: \"Invalid CSRF token, with ID: favourite. Is token a string?: 1\" at AbstractController.php line 40","context":{"exception":{"class":"Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException","message":"Invalid CSRF token, with ID: favourite. Is token a string?: 1","code":0,"file":"/var/www/kbin.melroy.org/html/src/Controller/AbstractController.php:40"}},"level":400,"level_name":"ERROR","channel":"request","datetime":"2024-09-14T15:10:01.670332+02:00","extra":{}}
{"message":"Uncaught PHP Exception Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException: \"Invalid CSRF token, with ID: favourite. Is token a string?: 1\" at AbstractController.php line 40","context":{"exception":{"class":"Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException","message":"Invalid CSRF token, with ID: favourite. Is token a string?: 1","code":0,"file":"/var/www/kbin.melroy.org/html/src/Controller/AbstractController.php:40"}},"level":400,"level_name":"ERROR","channel":"request","datetime":"2024-09-14T15:10:02.069033+02:00","extra":{}}
```

**Comment by BentiGorlich** [comment]
Could it be a problem the antispam bundle as well?


Am 14. September 2024 15:30:32 MESZ schrieb Melroy van den Berg ***@***.***>:

**Comment by melroy89** [comment]
> Could it be a problem the antispam bundle as well?

Nah, our anti-spam bundle is only implemented on two forms: Registration form & contact form... Also I would expect to see another error message in that case. What  you see above is an invalid CSRF.. Most likely due to caching.. or <unknown>.

**Comment by osaerisxero** [comment]
This happens to me fairly regularly, but i _believe_ only on mobile, which I use via webclip on Android with Firefox as the browser. Are you wanting the uri of the error page when it occurs?

**Comment by melroy89** [comment]
> This happens to me fairly regularly, but i _believe_ only on mobile, which I use via webclip on Android with Firefox as the browser. Are you wanting the uri of the error page when it occurs?

Thanks for responding!

@osaerisxero  Sorry, webclip? webclip is apple I think. But maybe you mean Progressive Web App (PWA) installed on the home screen of your Android device using Firefox?

Any info would help, like:

- What is the instance you are using? kbin.melroy.org or something else?
- What android version?
- Firefox or a special fork of Firefox?
- Do you mean you installed it as a PWA application on your android home screen?
- What is the full URL when this happens?
- Do you get an error page or are you logged-out?
- What action did you perform before this happened? Like voting, boost or anything else?..
- Anything else I couldn't think of right now.. If you can share more info the better (the only thing I don't need to know is your pincode 😆 )

**Comment by osaerisxero** [comment]
Ha, yes, I mean PWA.

Firefox version 130.0 (Build #2016041319), hg-b73ccdf1f861+

KES extension version 4.2.1

@osaerisxero@kbin.melroy.org

The URL does match the choice=1 format when it happens iirc, but I will need to look up how to make the pwa session expose the url bar and/or dev tools so i can provide a full one or a peek at the browser console. I should have some free time this evening to tinker with it.

**Comment by osaerisxero** [comment]
Amusingly it happened 2 upvotes after I sent the prior message. I'm going to switch to being in the full browser for the rest of the afternoon to see if I can get the error to pop there.

**Comment by melroy89** [comment]
> Amusingly it happened 2 upvotes after I sent the prior message. I'm going to switch to being in the full browser for the rest of the afternoon to see if I can get the error to pop there.

I was following the logs live at the moment. So I got the exact errors you experienced I believe. These seems to be coming from "favourite" which is indeed when you upvote a comment in a thread for example:

```json
{"message":"Uncaught PHP Exception Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException: \"Invalid CSRF token, with ID: favourite. Is token a string?: 1\" at AbstractController.php line 40","context":{"exception":{"class":"Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException","message":"Invalid CSRF token, with ID: favourite. Is token a string?: 1","code":0,"file":"/var/www/kbin.melroy.org/html/src/Controller/AbstractController.php:40"}},"level":400,"level_name":"ERROR","channel":"request","datetime":"2024-09-14T20:09:02.740028+02:00","extra":{}}
{"message":"Uncaught PHP Exception Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException: \"Invalid CSRF token, with ID: favourite. Is token a string?: 1\" at AbstractController.php line 40","context":{"exception":{"class":"Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException","message":"Invalid CSRF token, with ID: favourite. Is token a string?: 1","code":0,"file":"/var/www/kbin.melroy.org/html/src/Controller/AbstractController.php:40"}},"level":400,"level_name":"ERROR","channel":"request","datetime":"2024-09-14T20:09:03.128857+02:00","extra":{}}
```

**Comment by osaerisxero** [comment]
It does proc on standard-browser-mode firefox.  I _should_ have hooked it up to a desktop browser for debugging before that, but I've got it hooked up now.  We'll see what we can see if I can get it to proc again before I have to stop working on this for a while :)

**Review by BentiGorlich — APPROVED** [review]

**Comment by melroy89** [comment]
Latest info of Jerry, the CSRF IDs that he is seeing in the error logs are:

- vote (down vote)
- favourite (up vote)
- subscribe

**Pull request merged**
