### PR TITLE
Add posting restricted to mods to the API

### PR DESCRIPTION
**Pull request by BentiGorlich**
Overlooked in #951

### CODE REVIEW

**Comment by BentiGorlich** [comment]
@jwr1 couldn't test it locally. I didn't find a way to edit a magazine in interstellar

**Review by nobodyatroot — APPROVED** [review]

**Comment by jwr1** [comment]
> @jwr1 couldn't test it locally. I didn't find a way to edit a magazine in interstellar

Unfortunately, there's no way to edit, or even moderate a magazine yet.

**Comment by BentiGorlich** [comment]
So you meant that you'd want to get that info from the MagazineRetrieveAPI. I'll add that :)

**Comment by BentiGorlich** [comment]
> Maybe that could be the next thing I work on.

If anything is missing or not working in the API just tell me and I'll fix it asap :)

**Review by jwr1 — APPROVED** [review]

**Pull request merged**
