### PR TITLE
Updating packages & recipes

### PR DESCRIPTION
**Pull request by melroy89**
This PR is mainly focusing on the remaining package updates and recipe updates.

It updates all `symfony/*` packages. And I ran recipe updates for: 

- symfony/framework-bundle
- symfony/web-profiler-bundle
- symfony/validator
- phpstan/phpstan
- symfony/messenger.

As well as fixing the indentation of the config yaml files (to 4 spaces), so future recipes will  (hopefully) merge easier.

### CODE REVIEW

**Comment by melroy89** [comment]
After this PR I focus again on actual error pollution and deprecation messages. Since now most packages are up to date.

**Comment by nobodyatroot** [comment]
> After this PR I focus again on actual error pollution and deprecation messages. Since now most packages are up to date.

I'll let this run for a couple hours, but I don't see any issues so far.

**Comment by melroy89** [comment]
Indeed. This time I didn't dare to touch the doctrine recipe yet haha. But also test it on my instance and testing boost and voting /favor

**Review by nobodyatroot — APPROVED** [review]
No issues observed during testing, looks good!

**Comment by melroy89** [comment]
U sure this time? 😄 Thanks!

**Comment by nobodyatroot** [comment]
kbin.run hasn't fallen over yet, so I think you're good to go.

**Pull request merged**
