### PR TITLE
comment reply position - translate top label text

### PR DESCRIPTION
**Pull request by e-five256**
focused a bit too much on missing loc entries and missed that top wasn't being translated at all. this translates it, which already existed for "Top" regarding posts. I'm not quite sure if the two usages have the same meanings in all languages so if they don't, we might want to break this out to be a different loc token

### CODE REVIEW

**Review by nobodyatroot — DISMISSED** [review]

**Comment by e-five256** [comment]
oops, sorry, looking at translations, it might be better to change the token after all, the translations for `top:` seem to be for "Outstanding", which makes sense. Maybe I should change this to `position_top` and change bottom as well before people translate it

**Comment by melroy89** [comment]
Or we just change the translation of top.

**Comment by e-five256** [comment]
It's used in post sorting (Top, Hot, New) etc. I think it makes sense to use two different loc tokens in this case, as non-English languages probably have distinct words for each

**Comment by melroy89** [comment]
I mean the other place where top is used, where apparently it is used in the context for "outstanding".

**Comment by e-five256** [comment]
Spanish (Outstanding), Italian (Better), Polish (Important), Chinese (Optimal), according to google translate. top definitely has multiple meanings in english so it makes sense it doesn't translate exactly for both scenarios

**Comment by melroy89** [comment]
Don't change other translation files apart from English. This will give issues in Weblate two-away sync. Only English is allow to be changed in the repository. [Weblate should be used for all translations](https://hosted.weblate.org/projects/mbin/)...

You're introducing regression now:

image

**Comment by e-five256** [comment]
Sorry about that, thanks for fixing it. I thought the concept of two-way meant changes on both ends worked for any files. I'm surprised it tries to take changes from branches, as I would've thought it'd only sync the default branch as tons of changes can happen while work is in progress on branches. And I guess there's no way to lock those files from changes on this end.

**Review by nobodyatroot — APPROVED** [review]

**Comment by e-five256** [comment]
@melroy89 does this change seem ok to you now? Don't want to make any mistakes with the localization files again. not sure what happens to the dutch translation if the english token is removed

**Comment by melroy89** [comment]
@e-five256 I was also surprised. I still do not recommend changing the translation files except for the English version to limit the sync issues. But it might have been just something strange sync bug on the github main branch and the weblate remote main branch. Yes it's fixed. I think the change is fine ... Let's see how it goes.

**Review by melroy89 — APPROVED** [review]

**Pull request merged**
