### PR TITLE
Add badges to admins, mods and OPs in comments

### PR DESCRIPTION
**Pull request by BentiGorlich**
Looks like this:
1. kbin theme:  grafik
2. light theme: grafik
3. dark theme: grafik
4. sunny light theme: grafik
5. sunny dark theme: grafik
6. Tokyo Night theme: grafik

### CODE REVIEW

**Comment by e-five256** [comment]
Would we want a label for global mods as well?

**Comment by BentiGorlich** [comment]
> Would we want a label for global mods as well? Edit, or maybe that's what `user.moderator()` is? I wonder if we'd want it to say something else if so, to clarify they aren't someone in the mod list in the sidebar but someone with global powers

Yes that exactly what the `user.moderator()` call is doing

**Comment by e-five256** [comment]
I think it'd be better to have a Global Mod label / translation in that case, at least in my opinion

**Review by e-five256 — APPROVED** [review]

**Comment by melroy89** [comment]
Love it!

**Pull request merged**
