### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Mbin/Mbin](https://hosted.weblate.org/projects/mbin/kbin/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by uandreew** [comment]
The translation is 100% fine, I don't know why Weblate put it is in the commit.

**Comment by melroy89** [comment]
UK stands for United Kingdom, but UA is for Ukraine according to ISO 3166 international standard. I think this needs to be changed in Weblate for sure.. ihorya?

**Comment by melroy89** [comment]
I will try to make changes in the main branch.

**Review by melroy89 — APPROVED** [review]

**Comment by zen-tools** [comment]
> UK stands for United Kingdom, but UA is for Ukraine according to ISO 3166 international standard. I think this needs to be changed in Weblate for sure.. ihorya/ Ігор Андреєв ?

uk is for the Ukranian language as defined by [ISO 639-1](http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)
UA is for the region of Ukraine as defined by [ISO 3166-1](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements)

However `UK` never means "United Kingdom", the correct region subtag to use for that is `GB`.

**Pull request merged**
