### PR TITLE
[Feature] Admin Signup Notifications

### LINKED ISSUE #838: Admin Notification for signups
**Is your feature request related to a problem? Please describe.**
I want to be notified when a user signs up, so I can check whether that user is a spam account or a real user

**Describe the solution you'd like**
A new notification only going to admins, created when a user signs up, after verifying their mail

**Describe alternatives you've considered**
none

**Additional context**
mastodon has that and it is super useful

### PR DESCRIPTION
**Pull request by BentiGorlich**
When a user is created send a notification to all admins

Notification:
grafik

Push Notification:
grafik

closes #838

### CODE REVIEW

**Comment by melroy89** [comment]
Could we please disable this feature at settings as well; `admin/settings`?

**Comment by BentiGorlich** [comment]
Never saw that message, sure I'll add it :)

**Comment by melroy89** [comment]
I see, you added it now to the user profile. aka `settings/general`?

**Review by melroy89 — APPROVED** [review]

**Comment by melroy89** [comment]
> yeah correct. Each admin account can enable/disable as they wish. It is on by default though. The option is not displayed to non admins

Yup! Perfect. I was just thinking like this is the first option for admins under the profile settings? I was a bit surprised to be honest 😆 . I was expecting to have more options for admins. But apparently not (yet).

**Pull request merged**
