### PR TITLE
Redirect to user profile settings on newly created SSO users

### LINKED ISSUE #890: After signing in with SSO, redirect to user profile
When signing in using an SSO, e.g. google, discord, if the username already exists it is made by adding a random number. This can only be changed until, for instance, an upvote is made.

Google based usernames are always made based on google name + random number

Instead of bringing the user to https://my.mbin it should bring them to https://my.mbin/settings/profile so they can change their username (maybe clarify that this can only be done until they interact)

### PR DESCRIPTION
**Pull request by CocoPoops**
Change all SSO providers to redirect to profile settings when the user is first created so that a user can change their username if their username already exists 

Closes #890

### CODE REVIEW

**Comment by melroy89** [comment]
Maybe only redirect to profile page when their username already exists?

**Comment by CocoPoops** [comment]
> Maybe only redirect to profile page when their username already exists?

i wasn't sure which way you guys would prefer as some of the authenticators add the random numbers and some check for existing users first before adding the random numbers
i assume their is a reason that some of them are that way 🤷

**Comment by nobodyatroot** [comment]
> > Maybe only redirect to profile page when their username already exists?
> 
> i wasn't sure which way you guys would prefer as some of the authenticators add the random numbers and some check for existing users first before adding the random numbers i assume their is a reason that some of them are that way 🤷

the whole thing is super inconsistent, but this seems to be a reasonable way to solve the issue at hand.

**Review by nobodyatroot — APPROVED** [review]
tested in dev, seems to work as expected. code changes seem reasonable.

**Pull request merged**
